---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    ignore:
      - dependency-name: "jsesh"
        versions:
          - "20130225"
          - "20110209"
          - "7.3.1"
          - "6.4.1"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jkatzwinkel"

  - package-ecosystem: "npm"
    directory: "/src/test/e2e"
    schedule:
      interval: "monthly"
    reviewers:
      - "jkatzwinkel"

...
