---

version: 2

updates:

  - package-ecosystem: "gradle"
    directory: "/"
    ignore:
      - dependency-name: "jsesh"
        versions:
          - "20130225"
          - "20110209"
          - "7.3.1"
          - "6.4.1"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:spring-boot-*"
          - "org.springframework.boot"
      junit:
        patterns:
          - "org.junit.jupiter:junit-jupiter-*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":dependabot"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 90
      include:
        - openjdk
      exclude:
        - gradle
    commit-message:
      prefix: ":dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":dependabot"

  - package-ecosystem: "npm"
    directory: "/src/test/e2e"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: ":dependabot"

...
