version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    ports:
      - ${ES_PORT}:9200
    stdin_open: true
    tty: true

  backend:
    depends_on:
      - elasticsearch
    build:
      context: https://github.com/jkatzwinkel/tla-es.git
      args:
        - es_port=${ES_PORT}
    ports:
      - ${BACKEND_PORT:?err}:8090
    tty: true
    network_mode: host

  app:
    depends_on:
      - backend
    build:
      context: .
    ports:
      - ${FRONTEND_PORT:?err}:8080
    tty: true
    network_mode: host
