---
version: '3.7'

services:

    frontend:
        container_name: tla-web
        build:
            context: .
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - ${LISTEN_PORT}:8080
        tty: true
        network_mode: host
        restart: unless-stopped

...
