---
version: '3.7'

services:

    es:
        container_name: tla-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        ports:
            - ${ES_PORT:-9200}:9200
        stdin_open: true
        tty: true
        restart: unless-stopped


    populate:
        container_name: tla-ingest
        depends_on:
            - es
        build:
            context: https://github.com/JKatzwinkel/tla-es.git#query-expansion
        environment:
            - ES_HOST=es
            - ES_PORT=9200
            - SAMPLE_URL
        tty: true
        command: "ingest"


    backend:
        container_name: tla-backend
        depends_on:
            - populate
        build:
            context: https://github.com/JKatzwinkel/tla-es.git#query-expansion
        environment:
            - ES_HOST=es
            - ES_PORT=9200
        ports:
            - ${BACKEND_PORT:-8090}:8090
        tty: true
        restart: unless-stopped


    frontend:
        container_name: tla-web
        build:
            context: .
        environment:
            - BACKEND_PORT=8090
            - BACKEND_HOST=backend
            - JQUERY_VERSION
            - COOKIEJS_VERSION
            - FONTAWESOME_VERSION
            - BOOTSTRAP_VERSION
        ports:
            - ${LISTEN_PORT:-8080}:8080
        tty: true
        restart: unless-stopped

...
