---

name: deploy

on: [pull_request]

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:

    - uses: "actions/checkout@v2"

    - name: start backend containers
      run: docker-compose up -d backend
      env:
        SAMPLE_URL: http://aaew64.bbaw.de/resources/tla-data/tla-sample-20210115-1000t.tar.gz
        ES_PORT: 9201
        BACKEND_PORT: 8090
        LISTEN_PORT: 8080

    - name: start frontend container
      run: docker-compose up -d frontend
      env:
        ES_PORT: 9201
        BACKEND_PORT: 8090
        LISTEN_PORT: 8080
        FONTAWESOME_VERSION: 5.12.1
        BOOTSTRAP_VERSION: 4.4.1
        JQUERY_VERSION: 3.5.1
        COOKIEJS_VERSION: 2.2.1

    - name: wait for frontend to respond
      uses: "cygnetdigital/wait_for_response@v2.0.0"
      with:
        url: http://localhost:8080
        responseCode: 200
        interval: 2000
        timeout: 60000

    - name: show tla-ingest container logs
      run: docker-compose logs populate

    - name: show tla-backend container logs
      run: docker-compose logs backend

    - name: curl frontend from shell
      run: curl -s localhost:8080/

    - name: wait for backend to be populated with corpus data
      uses: "cygnetdigital/wait_for_response@v2.0.0"
      with:
        url: http://localhost:8090/lemma/get/100690
        responseCode: 200
        interval: 5000
        timeout: 100000

    - name: query backend endpoint URL paths list
      run: curl -s localhost:8090/

    - name: query backend version info
      run: curl -s localhost:8090/version

    - name: screenshot lemma search results page
      uses: "flameddd/screenshots-ci-action@v1.1.1"
      with:
        url: http://localhost:8080/lemma/search/
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        type: png

    - name: upload screenshots
      uses: "actions/upload-artifact@v2"
      with:
        path: screenshots
        name: lemma-search

    - name: screenshot lemma details page
      uses: "flameddd/screenshots-ci-action@v1.1.1"
      with:
        url: http://localhost:8080/lemma/100690
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        type: png

    - name: upload screenshots
      uses: "actions/upload-artifact@v2"
      with:
        path: screenshots
        name: lemma-details

    - name: screenshot sentence details page
      uses: "flameddd/screenshots-ci-action@v1.1.1"
      with:
        url: http://localhost:8080/sentence/IBUBdQmK4memIEBelX9qTCsmuS8#IBUBdzrGyezPxknfiltJIvlQAn0
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        type: png

    - name: upload screenshots
      uses: "actions/upload-artifact@v2"
      with:
        path: screenshots
        name: sentence-details

    - name: screenshot ths details page
      uses: "flameddd/screenshots-ci-action@v1.1.1"
      with:
        url: http://localhost:8080/thesaurus/7pupjz
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        type: png

    - name: upload screenshots
      uses: "actions/upload-artifact@v2"
      with:
        path: screenshots
        name: ths-details

    - name: screenshot sentence search form
      uses: "flameddd/screenshots-ci-action@v1.1.1"
      with:
        url: "http://localhost:8080/search?sentence&tokens[0].lemma.id=d2978&tokens[1].lemma.id=10070"
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
        type: png

    - name: upload screenshots
      uses: "actions/upload-artifact@v2"
      with:
        path: screenshots
        name: sentence-search-form

...
