---

name: dependencies

'on':
  push:
    branches: [main]

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 21

      - uses: mikepenz/gradle-dependency-submission@v0.9.0

...
