---

name: dependencies

'on':
  push:
    branches: [main]

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.3

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21

      - name: setup gradle dependency graph submission
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          dependency-graph: generate-and-submit

      - name: run gradle so that dependency graph gets generated
        run: ./gradlew compilejava --no-daemon

...
