---

name: update gradle wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: update gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          pr-title-template: >-
            :dependabot: Update Gradle Wrapper from %sourceVersion%
            to %targetVersion%
          commit-message-template: >-
            :dependabot: update gradle wrapper from %sourceVersion%
            to %targetVersion%
          labels: dependencies, gradle
          reviewers: jkatzwinkel

...