---

name: update gradle wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.changed }}
      ref: ${{ steps.ref.outputs.ref }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: update gradle wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2.1.0
        with:
          pr-title-template: >-
            :dependabot: Update gradle wrapper from %sourceVersion%
            to %targetVersion%
          commit-message-template: >-
            :dependabot: update gradle wrapper from %sourceVersion%
            to %targetVersion%
          labels: dependencies, gradle
          reviewers: JKatzwinkel
          release-channel: stable

      - name: determine change status
        id: changed
        run: |
          chg=$(git diff --shortstat HEAD..main | wc -l)
          echo "changed=${chg}" >> ${GITHUB_OUTPUT}

      - name: get branch name && save ref
        id: ref
        run: |
          branch=$(git branch --show-current)
          echo "ref=refs/heads/${branch}" >> ${GITHUB_OUTPUT}


  test:
    needs:
      - update-gradle-wrapper
    uses: ./.github/workflows/gradle.yml
    if: needs.update-gradle-wrapper.outputs.changed != '0'
    with:
      ref: ${{ needs.update-gradle-wrapper.outputs.ref }}

...
